stages:
  - make_assets
  - embed_reveal
  - docusaurus

build_dir: /build
output_type: last
output_dir: /output

make_assets:
  plugin: command
  options:
    command: make
    locations:
      - content/chapters/compute/lecture
    args:
      - all

embed_reveal:
  plugin: reveal_embed
  options:
    target: docusaurus
    extension: mdx
    build:
      Compute: Compute

docusaurus:
  plugin: docusaurus
  options:
    course_name: SO
    sidebar: js
    structure:
      - Lecture:
        - Compute:
            name: Compute
            location: /build/embed_reveal/Compute
      - Lab:
        - Compute:
            location: content/chapters/compute/lab
            name: README
    static_assets:
      - Compute: /build/make_assets/content/chapters/compute/lecture/_site
    config_meta:
      title: Operating Systems
      url: http://localhost/
      baseUrl: /operating-systems-oer/
      onBrokenLinks: warn
      onBrokenMarkdownLinks: warn
    config_socials:
      Main site: https://curs.upb.ro
      OCW: https://ocw.cs.pub.ro/courses/so
      Facebook: https://www.facebook.com/sisteme.de.operare/
    copyright_string: SO Team
